kind: Deployment
apiVersion: apps/v1
metadata:
  name: cat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
        - name: cat
          image: 'docker-nexus-edu.tn.hr/animals:latest'
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          env:
            - name: ANIMAL
              value: cat
            - name: DB_HOST
              value: animalsdb
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: animal
            - name: DB_PASSWORD
              value: 4n1m4l!
            - name: DB_NAME
              value: animals
          imagePullPolicy: Always
      imagePullSecrets:
        - name: nexus-pull-secret
