kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: animal-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-file-bronze-gid
  volumeMode: Filesystem
